##################################################################
#                          YEAH LARAVEL                          #
##################################################################
version: "3"
services:
  mariadb:
    build:
      context: ./mariadb
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - MARIADB_VERSION=${MARIADB_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - TZ=${TIMEZONE}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
  proxy:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./nginx/proxy/nginx.conf:/etc/nginx/nginx.conf
  web:
    image: nginx:latest
    expose:
      - "8080"
    volumes:
      - ../:/var/www:cached
      - ./nginx/web/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/web/sites-available:/etc/nginx/sites-available
      - ./nginx/web/ssl:/etc/nginx/ssl
  php:
    build:
        context: .
        dockerfile: php-fpm/Dockerfile
    volumes:
      - ../:/var/www:cached
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
